spring.application.name=exam-management-system

spring.datasource.url=jdbc:mysql://localhost:3306/exam_management_db
spring.datasource.username=root
spring.datasource.password=6301251498@Ma

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# JWT Configuration
jwt.secret=MzJieXRlc2xvbmdzZWNyZXRrZXlmb3Jqd3RzaWduaW5nMTIzNDU2
jwt.expiration=3600000

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=madhugaddam092@gmail.com
spring.mail.password=dhil gsvi qpot nneh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true